/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LecturesRouteImport } from './routes/lectures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsMockRouteImport } from './routes/tests.mock'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesRoute = LecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsMockRoute = TestsMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => TestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lectures': typeof LecturesRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/tests': typeof TestsRouteWithChildren
  '/tests/mock': typeof TestsMockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lectures': typeof LecturesRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/tests': typeof TestsRouteWithChildren
  '/tests/mock': typeof TestsMockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lectures': typeof LecturesRoute
  '/login': typeof LoginRoute
  '/papers': typeof PapersRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/tests': typeof TestsRouteWithChildren
  '/tests/mock': typeof TestsMockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lectures'
    | '/login'
    | '/papers'
    | '/profile'
    | '/signup'
    | '/tests'
    | '/tests/mock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lectures'
    | '/login'
    | '/papers'
    | '/profile'
    | '/signup'
    | '/tests'
    | '/tests/mock'
  id:
    | '__root__'
    | '/'
    | '/lectures'
    | '/login'
    | '/papers'
    | '/profile'
    | '/signup'
    | '/tests'
    | '/tests/mock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LecturesRoute: typeof LecturesRoute
  LoginRoute: typeof LoginRoute
  PapersRoute: typeof PapersRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TestsRoute: typeof TestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures': {
      id: '/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof LecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/mock': {
      id: '/tests/mock'
      path: '/mock'
      fullPath: '/tests/mock'
      preLoaderRoute: typeof TestsMockRouteImport
      parentRoute: typeof TestsRoute
    }
  }
}

interface TestsRouteChildren {
  TestsMockRoute: typeof TestsMockRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsMockRoute: TestsMockRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LecturesRoute: LecturesRoute,
  LoginRoute: LoginRoute,
  PapersRoute: PapersRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TestsRoute: TestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
